### ISSUE TITLE
WIP Status

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Plugin.WindowsSettings#5]
Hey guys @taooceros @pc223 , what's the progress status with this plugin, i see only one pr not a draft, and are we ready to merge this with the control panel plugin?

Anything I can help finish off?

**Comment by taooceros** [comment]
I previously thought we may add this in 1.9.0, so considering finish this after a while😅. 
However, obviously I have forgot it😨.

**Comment by taooceros** [comment]
I think after merging the pull request from @pc223, the only thing that control panel left is translation. Though, @pc223 has provided a way to create translation files, so probably we can merge it in the future.

**Comment by pc223** [comment]
Not complete but usable, with a bit touch up I think it's ready for a early release build 👍 I use this more than a month now, no bugs yet 😄

**Comment by pc223** [comment]
> I think after merging the pull request from @pc223, the only thing that control panel left is translation. Though, @pc223 has provided a way to create translation files, so probably we can merge it in the future.

I still don't how to work with resx file yet, but if you can work with these json files like these 3 files: https://github.com/pc223/MSWindowsControlPanelTaskLinks, convert them to resx. I can generate for you around 20-30 languages, got a script to automate it so ezpz 😎

```json
{
  "schema_version": "0.0.1",
  "language": "fr_FR",
  "windows_version": "19043.1055",
  "items": [
    {
      "name": "Ex\u00e9cuter le module d\u2019apprentissage de votre voix",
      "cmd": "%%windir%\\system32\\rundll32.exe %windir%\\system32\\speech\\speechux\\SpeechUX.dll,RunWizard UserTraining",
      "keywords": [
        [
          "pr\u00e9cis",
          "precis",
          "exact",
          "pr\u00e9cision",
          "exactitude",
          "pr\u00e9cis\u00e9ment",
          "precisement",
          "exactement",
          "exact",
          "erreurs",
          "fautes",
          "accuracy",
          "accurately",
          "precise",
          "precision",
          "correct",
          "mistakes"
        ],
        [
          "ordinateur",
          "mon ordinateur",
          "monordinateur",
          "ordinateur personnel",
          "ordinateurpersonnel",
          "syst\u00e8me",
          "portable",
          "compuer",
          "machine",
...
```

**Comment by taooceros** [comment]
Hmmm the resx file is a set of key-value, so we need to figure a way to find the same key. Is that file only include tasklink translation?

**Comment by taooceros** [comment]
I found that I can grab the translation from powertoy xd
For the tasklink, let me think how to translate it later

**Comment by jjw24** [comment]
let's move over to https://github.com/Flow-Launcher/Flow.Launcher/pull/741
